import { Category, Task } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'work',
    name: '핵심업무',
    color: 'bg-rose-50/90 text-rose-950 border-rose-200',
    dotColor: 'bg-rose-700',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-950',
  },
  {
    id: 'strategy',
    name: '전략기획',
    color: 'bg-slate-100 text-slate-900 border-slate-300',
    dotColor: 'bg-slate-700',
    badgeBg: 'bg-slate-200',
    badgeText: 'text-slate-900',
  },
  {
    id: 'operation',
    name: '운영관리',
    color: 'bg-emerald-50/80 text-emerald-950 border-emerald-200',
    dotColor: 'bg-emerald-700',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-950',
  },
  {
    id: 'finance',
    name: '재무회계',
    color: 'bg-amber-50/80 text-amber-950 border-amber-200',
    dotColor: 'bg-amber-700',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-950',
  },
];

export const CATEGORY_PRESET_COLORS = [
  { name: '버건디 뮤트 (핵심업무)', color: 'bg-rose-50/90 text-rose-950 border-rose-200', dotColor: 'bg-rose-700', badgeBg: 'bg-rose-100', badgeText: 'text-rose-950' },
  { name: '슬레이트 네이비 (전략기획)', color: 'bg-slate-100 text-slate-900 border-slate-300', dotColor: 'bg-slate-700', badgeBg: 'bg-slate-200', badgeText: 'text-slate-900' },
  { name: '올리브 뮤트 (운영관리)', color: 'bg-emerald-50/80 text-emerald-950 border-emerald-200', dotColor: 'bg-emerald-700', badgeBg: 'bg-emerald-100', badgeText: 'text-emerald-950' },
  { name: '앰버 뮤트 (재무회계)', color: 'bg-amber-50/80 text-amber-950 border-amber-200', dotColor: 'bg-amber-700', badgeBg: 'bg-amber-100', badgeText: 'text-amber-950' },
  { name: '인디고 뮤트 (프로젝트)', color: 'bg-indigo-50/80 text-indigo-950 border-indigo-200', dotColor: 'bg-indigo-700', badgeBg: 'bg-indigo-100', badgeText: 'text-indigo-950' },
  { name: '웜 스톤 (일반/기타)', color: 'bg-stone-100 text-stone-900 border-stone-200', dotColor: 'bg-stone-600', badgeBg: 'bg-stone-200', badgeText: 'text-stone-900' },
];

// Helper to get today's date formatted as YYYY-MM-DD
const getTodayStr = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: '주간 부서 경영실적 보고서 작성 및 취합',
    description: '각 파트별 핵심 실적 및 차주 목표 검토 후 임원진 보고',
    date: getTodayStr(0),
    startTime: '09:30',
    endTime: '11:00',
    categoryId: 'work',
    importance: 'A',
    urgency: '상',
    status: 'in_progress',
    progress: 60,
    allDay: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: '오후 2시 전략기획실 연간 예산안 검토 회의',
    description: '회의실 A (본관 12층), 재무제표 및 손익계산서 지참',
    date: getTodayStr(0),
    startTime: '14:00',
    endTime: '15:30',
    categoryId: 'work',
    importance: 'A',
    urgency: '상',
    status: 'todo',
    progress: 0,
    allDay: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: '부서내 오피스 런치 미팅 및 신규 프로젝트 브리핑',
    description: '구내식당 또는 대회의실 도시락 미팅',
    date: getTodayStr(0),
    startTime: '12:00',
    endTime: '13:00',
    categoryId: 'daily',
    importance: 'C',
    urgency: '중',
    status: 'completed',
    progress: 100,
    allDay: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    title: '퇴근 후 사내 휘트니스 센터 (근력 및 유산소)',
    description: '컨디션 조절 및 체력 관리',
    date: getTodayStr(0),
    startTime: '19:00',
    endTime: '20:30',
    categoryId: 'exercise',
    importance: 'D',
    urgency: '하',
    status: 'todo',
    progress: 0,
    allDay: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    title: '당일 업무 마감 점검 및 익일 일정 조율',
    description: '미결재 문서 확인 및 To-Do 우선순위 갱신',
    date: getTodayStr(0),
    startTime: '17:30',
    endTime: '18:00',
    categoryId: 'work',
    importance: 'B',
    urgency: '중',
    status: 'todo',
    progress: 0,
    allDay: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-6',
    title: '글로벌 비즈니스 영어 협상 세미나 수강',
    description: '온라인 강의실 수강 및 리포트 작성',
    date: getTodayStr(1),
    startTime: '21:00',
    endTime: '22:00',
    categoryId: 'study',
    importance: 'C',
    urgency: '중',
    status: 'todo',
    progress: 0,
    allDay: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-7',
    title: '신규 보안 솔루션 도입 타당성 검토',
    description: 'IT보안팀 합동 TF 회의',
    date: getTodayStr(2),
    startTime: '10:00',
    endTime: '12:00',
    categoryId: 'work',
    importance: 'B',
    urgency: '상',
    status: 'todo',
    progress: 0,
    allDay: false,
    createdAt: new Date().toISOString(),
  }
];
